---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - watch
- apiGroups:
  - webapp.csye7125-su24-team14
  resources:
  - githubreleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.csye7125-su24-team14
  resources:
  - githubreleases/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.csye7125-su24-team14
  resources:
  - githubreleases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - webapp.csye7125-su24-team14
  resources:
  - githubreleasesmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.csye7125-su24-team14
  resources:
  - githubreleasesmonitors/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.csye7125-su24-team14
  resources:
  - githubreleasesmonitors/status
  verbs:
  - get
  - patch
  - update
