apiVersion: webapp.csye7125-su24-team14/v1
kind: GitHubReleasesMonitor
metadata:
  labels:
    app.kubernetes.io/name: cve-operator
    app.kubernetes.io/managed-by: kustomize
  name: githubreleasesmonitor-sample
spec:
  # TODO(user): Add fields here
  url: "https://api.github.com/repos/CVEProject/cvelistV5/releases"
  monitorFrom: "2024-07-20"
  schedule: "*/1 * * * *"

